services:
  postgres:
    container_name: datamodeling5
    image: postgres:16
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
